name: Shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo commands
        run: eccho "Hello World!"
      - name: multiline script
        run: |
          npm -v
          node -v