name: Container Docker
on: push

jobs:
  node-docker-services:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: node Version
        run: node -v
  node-docker1: 
    runs-on: ubuntu-latest
    container: 
      image: node:17.9.1-slim
    steps:
      - name: Log node Version
        run: |
          node -v 
          cat /etc/os-release
