name: Container Docker
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: 
  node-docker: 
    runs-on: ubuntu-latest
    container: 
      image: node:17.9.1-slim
    steps:
      - name: Log node Version
        run: |
          node -v 
          cat /etc/os-release
