name: Container Docker
on: push

jobs:
  node-docker: 
    runs-on: ubuntu-latest
    container: 
      image: node:17.9.1-slim
    steps:
      - name: Log node Version
        run: |
          node v 
          cat /etc/os-release
