name: Hello world Java script

on: [pull_request]

jobs:
  run-js-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: list all Files for PR
        run: |
          pwd
          ls -la
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"    
      - name: checkout files
        uses: actions/checkout@v2
      - name: list all Files
        run: |
          pwd
          ls -la    
      - name: start the js actions/checkout
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "krishna"
      - name: output of the actions
        run: echo "${{steps.greet.outputs.time}}"
