name: Shell commands

<<<<<<< master
on: push
=======

  
on: 
  # schedule:
  #   - cron: "0/5 * * * *"
  # #pull_request:
  repository_dispatch:
    types: [build]

    
>>>>>>> local

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: multilines script
        run: |
          node -v
          npm -v
      - name: python commands
        shell: python
        run: |
          import platform
          import pip
          print(platform.processor())
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: windows directory path
        run: get-location
      - name: powershell directory location 
        run: pwd
        shell: bash
        
